# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# proto-file: falken/service/proto/action.proto
# proto-message: ActionSpec
actions {
  name: "switch_weapon"
  category {
    enum_values: "NO_SWITCH"
    enum_values: "KNIFE"
    enum_values: "PISTOL"
    enum_values: "SHOTGUN"
  }
}
actions {
  name: "throttle"
  number {
    minimum: -1.0
    maximum: 1.0
  }
}
actions {
  name: "joy_pitch_yaw"
  joystick {
    axes_mode: DELTA_PITCH_YAW
    controlled_entity: "player"
  }
}
actions {
  name: "joy_xz"
  joystick {
    axes_mode: DIRECTION_XZ
    controlled_entity: "player"
    control_frame: "camera"
  }
}
actions {
  name: "joy_xz_world"
  joystick {
    axes_mode: DIRECTION_XZ
    controlled_entity: "camera"
    control_frame: ""
  }
}
